### ISSUE TITLE
Data download script

### ISSUE THREAD

**Issue by ch-shin** [mlfoundations/dclm#18]
Hi team! It seems datasets are released in huggingface (e.g. https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x)
I was wondering if download script will be provided as in datacomp-clip (https://github.com/mlfoundations/datacomp/blob/main/download_upstream.py) or we should implement our own download script since some data filtering can be applied with some metadata before downloading

Thank you!

**Comment by GeorgiosSmyrnis** [comment]
Hi @ch-shin !

Thank you for your interest! We are planning to provide a download script similar to datacomp-clip, but that will be just data download without filtering on the fly (since we are ideally aiming to have a consistent tool set for all our submissions, to encourage reproducibility).

I personally think it's ok if such on the fly filtering is applied to increase compute efficiency, but in any of your submissions we encourage you to include such download code, since it would be part of the filtering pipeline (see also Appendix C of our [paper](https://arxiv.org/pdf/2406.11794) for the full rules of the benchmark).

**Comment by ch-shin** [comment]
Hi @GeorgiosSmyrnis , Thank you for your detailed answer!
