### ISSUE TITLE
The lack of the experimental environment introduction in the paper

### ISSUE THREAD

**Issue by flyflypeng** [mlfoundations/dclm#49]
Thank you very much for such a detailed introduction to data curation and providing open-source code.

However, in the paper, I couldn't find information about the experimental testing environment, specifically what type and how many CPUs and GPUs were used to process the DCLM-baseline dataset?

**Comment by afang-story** [comment]
We do not use GPUs for processing the dataset. We spin up ray clusters of CPUs from AWS and use it to do HTML extraction, RW v2 processing, and fast-text scoring. The specific instance matters less because these steps are easily parallelizable with our provided python code, but these steps vary in terms of computational requirements. For deduplication, we do this in a sharded manner to reduce computational requirements and use rust code.

**Comment by flyflypeng** [comment]
@afang-story Could you provide the data how much CPU resources your are using?

**Comment by afang-story** [comment]
I am sorry but we do not have the specific number of cpu hours readily available.

**Comment by flyflypeng** [comment]
Thanks anyway!
