### ISSUE TITLE
About the `--num_checkpoints` argument in pretraining

### ISSUE THREAD

**Issue by Yu-Shi** [mlfoundations/dclm#61]
Hello authors, thanks for your great work! I'm trying to use the code for pre-training. I notice that there is an argument `--num_checkpoints` in training.train, which is used to set the number of epochs to train,

https://github.com/mlfoundations/dclm/blob/d4ea9c5abfc42de04ad0c823ddf15ba4bcace1ac/training/params.py#L278-L279

, and, to set the number of training examples (tokens):

https://github.com/mlfoundations/dclm/blob/d4ea9c5abfc42de04ad0c823ddf15ba4bcace1ac/training/params.py#L319-L330

And it is set to 5 by default. Does that mean that the default setup is to train for 5 epochs on 1/5 of the data?

**Comment by GeorgiosSmyrnis** [comment]
Hi @Yu-Shi,

Thank you for the interest in our work!

The effect of these choices is that ~5 checkpoints are made, each on a different portion of the data (instead of 5 epochs on 1/5 of the data). This is due to a small issue with what the `--epochs` parameter means in open_lm - hence why it was renamed in this repo to more properly reflect its actual use (i.e. attempt to make ~5 checkpoints).

Let us know if this clarifies things!

**Comment by Yu-Shi** [comment]
@GeorgiosSmyrnis Got it, thanks for your reply!
