### ISSUE TITLE
Need multi-node training script example

### ISSUE THREAD

**Issue by LeoXinhaoLee** [mlfoundations/dclm#70]
Hi, thank you so much for releasing code for this great work!

I noticed that the training example command provided in README seems to only work for single node training. I'm wondering if you could kindly provide some examples about launching multi-node training with this codebase?

Thank you very much for your help!

**Comment by GeorgiosSmyrnis** [comment]
Hi @LeoXinhaoLee !

I think that if the environment variables `MASTER_ADDR` and `MASTER_PORT` have been set up correctly (so that they point to the main node from all the worker nodes), then launching the given command on all the nodes should work as planned. If not, you can also try setting the `torchrun` variable `--nnodes` explicitly.

If the cluster where you are running the multi-node training is a SLURM cluster, you can also use `srun training/train.py ...` in your script, and it will launch the job as normal.

**Comment by LeoXinhaoLee** [comment]
Thank you for your reply. I just made it work on a SLRUM cluster. Thanks again.
